# Setup
title:               Sugarcane DR
tagline:             'Data Repository of Sugarcane Breeding Program of UFV'
description:         'A reserved '
url:                 http://sugarcaneufv.github.io/sdr
baseurl:             '/'
paginate:            5

# About/contact
author:
  name:              Pedro MP Vidigal
  url:               https://pmvidigal.github.io
  email:             pedro.vidigal@ufv.br

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0.0
google_analytics_id: #UA-XXXX-Y
