# Setup
title:               Sugarcane DR
tagline:             'SDR'
description:         'Data Repository of Sugarcane Breeding Program of UFV'
url:                 https://sugarcaneufv.github.io
baseurl:             '/'
paginate:            5

# About/contact
author:
  name:              Pedro MP Vidigal
  url:               https://pmvidigal.github.io

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0
google_analytics_id: #UA-XXXX-Y
